var data = 
{
  "codes": [],
  "defs": [
    "$ Gyazoで#{params}を検索する {3}",
    "% open https://gyazo.com/search/'#{$1}' {3}",
    "$ Amazonのパスワードを計算 {4}",
    "% open http://pitecan.com/p/Amazon_masui@pitecan.com.html {4}",
    "$ 今いる場所の地図を開く {5}",
    "$ 現在地の地図を見る {5}",
    "$ 自分がどこにいるのか調べる {5}",
    "$ 自分の場所を調べる {5}",
    "% whereami {5}",
    "$ Amazon新刊漫画ランキング {6}",
    "% open https://www.amazon.co.jp/gp/new-releases/books/2501045051/ {6}",
    "$ Compare (#{files}) with the one from (#{numbers}) minutes ago {8}",
    "$ 「(#{files})」ファイルを(#{numbers})分前の(もの|バージョン)と#{compare} {8}",
    "$ 「(#{files})」ファイルが(#{numbers})分前から(変化した|変わった)ところを(#{display}) {8}",
    "% git diff HEAD '@{#{$2} minutes ago}' #{$1} {8}",
    "$ (#{numbers})分前の「(#{files})」ファイルと現在の(もの|バージョン)を#{compare} {8}",
    "% git diff HEAD '@{#{$1} minutes ago}' #{$2} {8}",
    "$ (#{numbers})日前の「(#{files})」ファイルと現在のものを#{compare} {8}",
    "% git diff HEAD '@{#{$1} days ago}' #{$2} {8}",
    "$ 現在の「(#{files})」ファイルを(#{numbers})日前のものを#{compare} {8}",
    "% git diff HEAD '@{#{$2} days ago}' #{$1} {8}",
    "$ (1つ|ひとつ)前のバージョンの(#{files})と#{compare} {8}",
    "$ (1つ|ひとつ)前のバージョンの(#{files})からの変更点 {8}",
    "% git diff $(git rev-list -n 1 HEAD -- #{$2})^ -- #{$2} {8}",
    "$ (#{files})を(1つ|ひとつ)前のバージョンと#{compare} {8}",
    "$ (#{files})の(1つ|ひとつ)前のバージョンからの変更点 {8}",
    "% git diff $(git rev-list -n 1 HEAD -- #{$1})^ -- #{$1} {8}",
    "$ (#{files})の最新版の変更点を(#{display}) {8}",
    "$ 最新の(#{files})の#{change}個所は? {8}",
    "$ (#{files})は最後にどこを変えた? {8}",
    "$ (#{files})の(一番新しい|最新の)#{change}は? {8}",
    "% git diff $(git rev-list -n 1 HEAD -- #{$1})^ -- #{$1} {8}",
    "$ (2つ|ふたつ)前のバージョンの(#{files})と#{compare} {8}",
    "$ (2つ|ふたつ)前のバージョンの(#{files})からの変更点を(#{display}) {8}",
    "% git diff $(git rev-list -n 2 HEAD -- #{$2})^^ -- #{$2} {8}",
    "$ (#{files})を(2つ|ふたつ)前のバージョンと#{compare} {8}",
    "$ (#{files})の(2つ|ふたつ)前のバージョンのからの#{change}を(#{display}) {8}",
    "% git diff $(git rev-list -n 2 HEAD -- #{$1})^^ -- #{$1} {8}",
    "$ 湘南台のラーメン情報 {9}",
    "% open https://scrapbox.io/SFCHelp/ラーメン {9}",
    "$ ASCIIコードを調べる {10}",
    "% open https://www.k-cube.co.jp/wakaba/server/ascii_code.html {10}",
    "$ ブランチ(のリスト)?を(#{display}) {11}",
    "% git branch {11}",
    "$ (#{params})というブランチを作成する {11}",
    "% git branch #{$1} {11}",
    "$ (#{branches})というブランチを(#{delete}) {11}",
    "% git branch -d #{$1} {11}",
    "$ ファイルを大きい(順に|順番で)表示する {13}",
    "$ ファイルを大きさの順に表示する {13}",
    "$ サイズの順に表示する {13}",
    "% git ls-files | xargs du -s | sort -r -n {13}",
    "$ ブランチを#{display} {14}",
    "% git branch {14}",
    "$ 「(#{params})」というブランチを作成する {14}",
    "% git branch #{$1} {14}",
    "$ 「(#{params})」というブランチを#{delete} {14}",
    "% git branch -d #{$1} {14}",
    "$ レポジトリの中身を(確認する|見る|調べる) {15}",
    "% ls .git {15}",
    "$ リモートレポジトリを確認する {15}",
    "% git remote -v {15}",
    "$ 新しい順にファイルをソートする {16}",
    "% ls -l -t {16}",
    "$ 大きさの順にファイルをソートする {16}",
    "% ls -l | sort -r -k 5 {16}",
    "$ 鎌倉の天気 {17}",
    "% open https://tenki.jp/forecast/3/17/4610/14204/3hours.html {17}",
    "$ ファイルの#{change}のランキングを#{display} {22}",
    "$ (よく|頻繁に)#{change}(されてる|されている)ファイルを#{display} {22}",
    "$ ファイルの#{change}頻度を#{display} {22}",
    "$ ファイルを#{change}頻度順にソート {22}",
    "% git log --name-only --pretty=\"format:\" | grep -ve \"^$\" | sort | uniq -c | sort -r {22}",
    "$ ファイルを新しい順に(リスト|表示)する {27}",
    "$ ファイルを新しさ順に(リスト|表示)する {27}",
    "$ 新しいファイルから順番に(リスト|表示)する {27}",
    "% git ls-files | xargs ls -l -t {27}",
    "$ ファイル「(#{files})」の編集履歴を完全に(#{delete})がワーキングツリーは残す {28}",
    "% git filter-branch -f --index-filter 'git rm --cached --ignore-unmatch #{$1}' HEAD {28}",
    "$ ファイル「(#{files})」の編集履歴を完全に(#{delete}) {28}",
    "% git filter-branch -f --index-filter 'git rm --ignore-unmatch #{$1}' HEAD {28}",
    "$ 編集履歴をGitHubに反映させる {28}",
    "% git push origin --force --all {28}",
    "$ ファイル「(#{files})」の(#{numbers})分前からの(#{change})履歴を(#{display}) {29}",
    "% git log --since \"#{$2} minutes ago\" #{$1} {29}",
    "$ (#{numbers})分前からのファイル「(#{files})」の(#{change})履歴を(#{display}) {29}",
    "% git log --since \"#{$1} minutes ago\" #{$2} {29}",
    "$ ファイル「(#{files})」の(#{numbers})分前からの(#{change})を(#{display}) {29}",
    "% git diff HEAD \"@{#{$2} minutes ago}\" #{$1} {29}",
    "$ (#{numbers})分前からのファイル「(#{files})」の(#{change})を(#{display}) {29}",
    "% git diff HEAD \"@{#{$1} minutes ago}\" #{$2} {29}",
    "$ ファイル「(#{files})」の(#{numbers})時間前からの(#{change})履歴を(#{display}) {29}",
    "% git log --since \"#{$2} hours ago\" #{$1} {29}",
    "$ (#{numbers})時間前からのファイル「(#{files})」の(#{change})履歴を(#{display}) {29}",
    "% git log --since \"#{$1} hours ago\" #{$2} {29}",
    "$ ファイル「(#{files})」の(#{numbers})時間前からの(#{change})を(#{display}) {29}",
    "% git diff HEAD \"@{#{$2} hours ago}\" #{$1} {29}",
    "$ (#{numbers})時間前からのファイル「(#{files})」の(#{change})を(#{display}) {29}",
    "% git diff HEAD \"@{#{$1} hours ago}\" #{$2} {29}",
    "$ ファイル「(#{files})」の(#{numbers})日前からの(#{change})履歴を(#{display}) {29}",
    "% git log --since \"#{$2} days ago\" #{$1} {29}",
    "$ (#{numbers})日前からのファイル「(#{files})」の(#{change})履歴を(#{display}) {29}",
    "% git log --since \"#{$1} days ago\" #{$2} {29}",
    "$ ファイル「(#{files})」の(#{numbers})日前からの(#{change})を(#{display}) {29}",
    "% git diff HEAD \"@{#{$2} days ago}\" #{$1} {29}",
    "$ (#{numbers})日前からのファイル「(#{files})」の(#{change})を(#{display}) {29}",
    "% git diff HEAD \"@{#{$1} days ago}\" #{$2} {29}",
    "$ ブランチのリストを更新日時順に表示する {30}",
    "% git branch --sort=committerdate {30}",
    "$ 直前のコミットを取り消す {32}",
    "% git reset --soft HEAD^ {32}",
    "$ ひとつ前のコミットの状態に完全に戻す {32}",
    "% git reset --hard HEAD^ {32}",
    "$ コミット後の変更を全部消す {32}",
    "% git reset --hard HEAD {32}",
    "$ すごい昔の状態で動作を確認したい {32}",
    "% git reset --hard 昔のコミットのハッシュ値 {32}",
    "$ 直前のリセットをなかったことにする {32}",
    "% git reset --hard ORIG_HEAD {32}",
    "$ 過去のあらゆる操作履歴を見る {33}",
    "% git reflog {33}",
    "$ 過去のコミット履歴を見る {33}",
    "% git log {33}",
    "$ 現在の編集状態を(#{display}) {39}",
    "$ 編集中のファイルを(#{display}) {39}",
    "% git status {39}",
    "$ (#{numbers})個前までのコミットをまとめる {43}",
    "% git rebase -i HEAD~#{$1} {43}",
    "$ ひとつ前の「(#{files})」ファイルを(#{display}) {44}",
    "$ 1バージョン前の「(#{files})」ファイルを(#{display}) {44}",
    "% git show HEAD~:#{$1} {44}",
    "$ ふたつ前の「(#{files})」ファイルを(#{display}) {44}",
    "$ 2バージョン前の「(#{files})」ファイルを(#{display}) {44}",
    "% git show HEAD~~:#{$1} {44}",
    "$ (#{numbers})個前の「(#{files})」ファイルを(#{display}) {44}",
    "$ (#{numbers})バージョン前の「(#{files})」ファイルを(#{display}) {44}",
    "% git show HEAD~#{$1}:#{$2} {44}",
    "$ (#{numbers})分前の「(#{files})」ファイルを(#{display}) {44}",
    "% git show '@{#{$1} minutes ago}':#{$2} {44}",
    "$ (#{numbers})時間前の「(#{files})」ファイルを(#{display}) {44}",
    "% git show '@{#{$1} hours ago}':#{$2} {44}",
    "$ (#{numbers})日前の「(#{files})」ファイルを(#{display}) {44}",
    "% git show '@{#{$1} days ago}':#{$2} {44}",
    "$ 昨日の「(#{files})」ファイルを(#{display}) {44}",
    "% git show @{yesterday}:#{$1} {44}",
    "$ (#{numbers})分前(から|以降に)(#{modified})ファイルをリストする {45}",
    "% git diff --name-only '@{#{$1} minutes ago}' {45}",
    "$ (#{numbers})時間前(から|以降に)(#{modified})ファイルをリストする {45}",
    "% git diff --name-only '@{#{$1} hours ago}' {45}",
    "$ (#{numbers})日前(から|以降に)(#{modified})ファイルをリストする {45}",
    "% git diff --name-only '@{#{$1} days ago}' {45}",
    "$ (#{numbers})日前からの変更を(#{display}) {45}",
    "% git log --stat --since=\"#{$1} days ago\" {45}",
    "$ 編集中のファイルをリストする {46}",
    "% git ls-files -m {46}",
    "$ (#{params})という文字列がはじめて出現した(バージョン|コミット)の情報を(#{display}) {47}",
    "% git log -1 `git rev-list --all | xargs git grep '#{$1}' | tail -1 | ruby -e \"STDIN.each {|line| puts line[0..39] }\"` {47}",
    "$ (#{params})という文字列がはじめて出現した(バージョン|コミット)に一時的に戻す {47}",
    "% git checkout `git rev-list --all | xargs git grep '#{$1}' | tail -1 | ruby -e \"STDIN.each {|line| puts line[0..39] }\"` {47}",
    "$ (#{numbers})個前のバージョンに一時的に戻す {48}",
    "% git checkout HEAD~#{$1} {48}",
    "$ (#{numbers})日前の状態に一時的に戻す {48}",
    "% git checkout \"@{#{$1} days ago}\"  {48}",
    "$ (#{numbers})時間前の状態に一時的に戻す {48}",
    "% git checkout \"@{#{$1} hours ago}\"  {48}",
    "$ (#{numbers})分前の状態に一時的に戻す {48}",
    "% git checkout \"@{#{$1} mins ago}\"  {48}",
    "$ 「(#{params})」という文字列を含むファイルを捜す {49}",
    "% git grep '#{$1}' {49}",
    "$ 「(#{params})」という文字列を含むファイルを全履歴から捜す {49}",
    "% git rev-list --all | xargs git grep '#{$1}' {49}",
    "$ ブランチ名を(#{params})に変える {50}",
    "% git branch -m #{$1} {50}",
    "$ (1つ|ひとつ)前のコミットで(削除した|消した)(#{files})を(復元する|元に戻す) {54}",
    "% git checkout $(git rev-list -n 1 HEAD -- #{$2})^ -- #{$2} {54}",
    "$ 現在の状況を(#{display}) {55}",
    "% git status {55}",
    "$ 「(#{files})」というファイルを「(#{params})」という名前に(変更|移動|改名|リネーム)する {56}",
    "% git mv #{$1} #{$2} {56}",
    "$ ファイル「(#{files})」を(#{delete}) {57}",
    "% git rm #{$1} {57}",
    "$ 直前のコミットのコメントを修正する {60}",
    "% git commit --amend {60}",
    "$ (#{files})に(#{params})という名前が(出現した|書かれた)のはいつ？ {61}",
    "% git blame #{$1} | grep #{$2} {61}",
    "$ (#{params})という名前が(#{files})に(出現した|書かれた)のはいつ？ {61}",
    "% git blame #{$2} | grep #{$1} {61}",
    "$ これまで追加/削除された行数を表示する {62}",
    "% git log --numstat --pretty=\"%H\" | awk 'NF==3 {plus+=$1; minus+=$2} END {printf(\"+%d, -%d\\\\n\", plus, minus)}' {62}",
    "$ (#{files})に(#{params})という名前が(出現した|書かれた)のはいつ？ {64}",
    "% git blame #{$1} | grep #{$2} {64}",
    "$ ツリー状にログを表示する {65}",
    "% git log --graph --all --format=\"%x09%an%x09%h %d %s\" {65}",
    "$ 最初に「(#{params})」という文字列を含むコミットをした時から現在までに追加されたファイルはどれとどれ？ {66}",
    "% git log --oneline --date=iso-strict --format='%cd %s' | grep #{$1} | tail -1 | awk '{print $1}' | xargs githelp-changed {66}"
  ],
  "pages": [
    "HelpLine",
    "Glossary",
    "HelpLineでサポートするヘルプ",
    "Gyazo画像を検索する",
    "Amazonのパスワードを計算",
    "自分の場所を調べる",
    "Amazon新刊漫画",
    "意義",
    "gitの古いファイルとの比較",
    "湘南台のラーメン",
    "ASCIIコード表",
    "gitのブランチの表示",
    "バージョン指定",
    "gitのファイルを大きい順に表示",
    "gitのブランチ",
    "gitレポジトリを確認する",
    "ファイルのソート",
    "鎌倉の天気",
    "やりたいことの例",
    "Issues",
    "Git情報源",
    "関連文献",
    "ファイルの編集回数のランキング",
    "★",
    "gem版の使い方",
    "gitコマンドに関する疑問",
    "Electron版GitHelp (2018版)",
    "新しい順にファイルを表示",
    "特定のファイルの履歴を消す",
    "最近の変更を知る",
    "ブランチのリストを更新日時順に表示する",
    "ファイルリスト",
    "Reset関連",
    "操作履歴",
    "branches",
    "タグ",
    "アイデア",
    "Gitのマニュアルページ",
    "このサイトについて",
    "編集中のファイル",
    "レポジトリ",
    "コミットID",
    "コミット",
    "コミットをまとめる",
    "古いファイル表示",
    "最近編集したファイルのリストを表示する",
    "編集中のファイルをリストする",
    "文字列がはじめて出現したバージョンを捜す",
    "古いバージョンに一時的に戻す",
    "変数や単語が出現しているファイルを捜す",
    "ブランチ名",
    "ユーザ情報",
    "引数パラメタ",
    "リモートブランチを消す",
    "ファイル復元",
    "現在の状況",
    "ファイル名変更",
    "ファイル削除",
    "テンプレート",
    "一時的に仕事を退避",
    "コメント修正",
    "文字列の出現を調べる",
    "追加/削除された行数",
    "数字パラメタ",
    "文字列の出現判定",
    "ツリー状にログを表示する",
    "ファイル追加",
    "args",
    "増井俊之"
  ]
}
module.exports = data
