var data = 
{
  "codes": [],
  "defs": [
    "$ ブランチを#{display} {7}",
    "% git branch {7}",
    "$ 「(#{params})」というブランチを作成する {7}",
    "% git branch #{$1} {7}",
    "$ 「(#{params})」というブランチを#{delete} {7}",
    "% git branch -d #{$1} {7}",
    "$ ファイルの#{change}のランキングを(#{display}) {10}",
    "$ (よく|頻繁に)#{change}(されてる|されている)ファイルを(#{display}) {10}",
    "$ ファイルの#{change}頻度を(#{display}) {10}",
    "$ ファイルを#{change}頻度順にソート {10}",
    "% git log --name-only --pretty=\"format:\" | grep -ve \"^$\" | sort | uniq -c | sort -r {10}",
    "$ レポジトリの中身を(確認する|見る|調べる) {12}",
    "% ls .git {12}",
    "$ リモートレポジトリを確認する {12}",
    "% git remote -v {12}",
    "$ ファイルを大きい(順に|順番で)表示する {13}",
    "$ ファイルを大きさの順に表示する {13}",
    "$ サイズの順に表示する {13}",
    "% git ls-files | xargs du -s | sort -r -n {13}",
    "$ ファイルを新しい順に(リスト|表示)する {14}",
    "$ ファイルを新しさ順に(リスト|表示)する {14}",
    "$ 新しいファイルから順番に(リスト|表示)する {14}",
    "% git ls-files | xargs ls -l -t {14}",
    "$ Compare file xxxx with the one from 2 days ago {15}",
    "$ xxxxというファイルを2日前のものと比較する {15}",
    "$ 2日前のxxxxというファイルを現在のものと比較する {15}",
    "% git diff HEAD '@{2 days ago}' xxxx {15}",
    "$ Compare (#{files}) with the one from (#{numbers}) minutes ago {15}",
    "$ 「(#{files})」ファイルを(#{numbers})分前の(もの|バージョン)と比較する {15}",
    "$ 「(#{files})」ファイルが(#{numbers})分前から(変化した|変わった)ところを(#{display}) {15}",
    "% git diff HEAD '@{#{$2} minutes ago}' #{$1} {15}",
    "$ (#{numbers})分前の「(#{files})」ファイルと現在の(もの|バージョン)を比較する {15}",
    "% git diff HEAD '@{#{$1} minutes ago}' #{$2} {15}",
    "$ (#{numbers})日前の「(#{files})」ファイルと現在のものを(比較する|比べる) {15}",
    "% git diff HEAD '@{#{$1} days ago}' #{$2} {15}",
    "$ 現在の「(#{files})」ファイルを(#{numbers})日前のものを(比較する|比べる) {15}",
    "% git diff HEAD '@{#{$2} days ago}' #{$1} {15}",
    "$ (1つ|ひとつ)前のバージョンの(#{files})と比較 {15}",
    "$ (1つ|ひとつ)前のバージョンの(#{files})からの変更点 {15}",
    "% git diff $(git rev-list -n 1 HEAD -- #{$2})^ -- #{$2} {15}",
    "$ (#{files})を(1つ|ひとつ)前のバージョンと比較 {15}",
    "$ (#{files})の(1つ|ひとつ)前のバージョンからの変更点 {15}",
    "% git diff $(git rev-list -n 1 HEAD -- #{$1})^ -- #{$1} {15}",
    "$ (#{files})の最新版の変更点を(#{display}) {15}",
    "$ 最新の(#{files})の変更個所は? {15}",
    "$ (#{files})は最後にどこを変えた? {15}",
    "$ (#{files})の(一番新しい|最新の)(変更|更新)は? {15}",
    "% git diff $(git rev-list -n 1 HEAD -- #{$1})^ -- #{$1} {15}",
    "$ (2つ|ふたつ)前のバージョンの(#{files})と比較 {15}",
    "$ (2つ|ふたつ)前のバージョンの(#{files})からの変更点を(#{display}) {15}",
    "% git diff $(git rev-list -n 1 HEAD -- #{$2})^^ -- #{$2} {15}",
    "$ (#{files})を(2つ|ふたつ)前のバージョンと比較 {15}",
    "$ (#{files})の(2つ|ふたつ)前のバージョンのからの変更点を(#{display}) {15}",
    "% git diff $(git rev-list -n 1 HEAD -- #{$1})^^ -- #{$1} {15}",
    "$ ファイル「(#{files})」の編集履歴を完全に(#{delete})がワーキングツリーは残す {16}",
    "% git filter-branch -f --index-filter 'git rm --cached --ignore-unmatch #{$1}' HEAD {16}",
    "$ ファイル「(#{files})」の編集履歴を完全に(#{delete}) {16}",
    "% git filter-branch -f --index-filter 'git rm --ignore-unmatch #{$1}' HEAD {16}",
    "$ 編集履歴をGitHubに反映させる {16}",
    "% git push origin --force --all {16}",
    "$ ファイル「(#{files})」の(#{numbers})分前からの(#{change})履歴を(#{display}) {17}",
    "% git log --since \"#{$2} minutes ago\" #{$1} {17}",
    "$ (#{numbers})分前からのファイル「(#{files})」の(#{change})履歴を(#{display}) {17}",
    "% git log --since \"#{$1} minutes ago\" #{$2} {17}",
    "$ ファイル「(#{files})」の(#{numbers})分前からの(#{change})を(#{display}) {17}",
    "% git diff HEAD \"@{#{$2} minutes ago}\" #{$1} {17}",
    "$ (#{numbers})分前からのファイル「(#{files})」の(#{change})を(#{display}) {17}",
    "% git diff HEAD \"@{#{$1} minutes ago}\" #{$2} {17}",
    "$ ファイル「(#{files})」の(#{numbers})時間前からの(#{change})履歴を(#{display}) {17}",
    "% git log --since \"#{$2} hours ago\" #{$1} {17}",
    "$ (#{numbers})時間前からのファイル「(#{files})」の(#{change})履歴を(#{display}) {17}",
    "% git log --since \"#{$1} hours ago\" #{$2} {17}",
    "$ ファイル「(#{files})」の(#{numbers})時間前からの(#{change})を(#{display}) {17}",
    "% git diff HEAD \"@{#{$2} hours ago}\" #{$1} {17}",
    "$ (#{numbers})時間前からのファイル「(#{files})」の(#{change})を(#{display}) {17}",
    "% git diff HEAD \"@{#{$1} hours ago}\" #{$2} {17}",
    "$ ファイル「(#{files})」の(#{numbers})日前からの(#{change})履歴を(#{display}) {17}",
    "% git log --since \"#{$2} days ago\" #{$1} {17}",
    "$ (#{numbers})日前からのファイル「(#{files})」の(#{change})履歴を(#{display}) {17}",
    "% git log --since \"#{$1} days ago\" #{$2} {17}",
    "$ ファイル「(#{files})」の(#{numbers})日前からの(#{change})を(#{display}) {17}",
    "% git diff HEAD \"@{#{$2} days ago}\" #{$1} {17}",
    "$ (#{numbers})日前からのファイル「(#{files})」の(#{change})を(#{display}) {17}",
    "% git diff HEAD \"@{#{$1} days ago}\" #{$2} {17}",
    "$ ブランチのリストを更新日時順に表示する {18}",
    "% git branch --sort=committerdate {18}",
    "$ 直前のコミットを取り消す {20}",
    "% git reset --soft HEAD^ {20}",
    "$ ひとつ前のコミットの状態に完全に戻す {20}",
    "% git reset --hard HEAD^ {20}",
    "$ コミット後の変更を全部消す {20}",
    "% git reset --hard HEAD {20}",
    "$ すごい昔の状態で動作を確認したい {20}",
    "% git reset --hard 昔のコミットのハッシュ値 {20}",
    "$ 直前のリセットをなかったことにする {20}",
    "% git reset --hard ORIG_HEAD {20}",
    "$ 過去のあらゆる操作履歴を見る {21}",
    "% git reflog {21}",
    "$ 過去のコミット履歴を見る {21}",
    "% git log {21}",
    "$ ブランチ(のリスト)?を(#{display}) {24}",
    "% git branch {24}",
    "$ (#{params})というブランチを作成する {24}",
    "% git branch #{$1} {24}",
    "$ (#{branches})というブランチを(#{delete}) {24}",
    "% git branch -d #{$1} {24}",
    "$ 現在の編集状態を(#{display}) {27}",
    "$ 編集中のファイルを(#{display}) {27}",
    "% git status {27}",
    "$ (#{numbers})個前までのコミットをまとめる {31}",
    "% git rebase -i HEAD~#{$1} {31}",
    "$ ひとつ前の「(#{files})」ファイルを(#{display}) {33}",
    "$ 1バージョン前の「(#{files})」ファイルを(#{display}) {33}",
    "% git show HEAD~:#{$1} {33}",
    "$ ふたつ前の「(#{files})」ファイルを(#{display}) {33}",
    "$ 2バージョン前の「(#{files})」ファイルを(#{display}) {33}",
    "% git show HEAD~~:#{$1} {33}",
    "$ (#{numbers})個前の「(#{files})」ファイルを(#{display}) {33}",
    "$ (#{numbers})バージョン前の「(#{files})」ファイルを(#{display}) {33}",
    "% git show HEAD~#{$1}:#{$2} {33}",
    "$ (#{numbers})分前の「(#{files})」ファイルを(#{display}) {33}",
    "% git show '@{#{$1} minutes ago}':#{$2} {33}",
    "$ (#{numbers})時間前の「(#{files})」ファイルを(#{display}) {33}",
    "% git show '@{#{$1} hours ago}':#{$2} {33}",
    "$ (#{numbers})日前の「(#{files})」ファイルを(#{display}) {33}",
    "% git show '@{#{$1} days ago}':#{$2} {33}",
    "$ 昨日の「(#{files})」ファイルを(#{display}) {33}",
    "% git show @{yesterday}:#{$1} {33}",
    "$ (#{numbers})分前(から|以降に)(#{modified})ファイルをリストする {34}",
    "% git diff --name-only '@{#{$1} minutes ago}' {34}",
    "$ (#{numbers})時間前(から|以降に)(#{modified})ファイルをリストする {34}",
    "% git diff --name-only '@{#{$1} hours ago}' {34}",
    "$ (#{numbers})日前(から|以降に)(#{modified})ファイルをリストする {34}",
    "% git diff --name-only '@{#{$1} days ago}' {34}",
    "$ (#{numbers})日前からの変更を(#{display}) {34}",
    "% git log --stat --since=\"#{$1} days ago\" {34}",
    "$ 編集中のファイルをリストする {35}",
    "% git ls-files -m {35}",
    "$ (#{params})という文字列がはじめて出現した(バージョン|コミット)の情報を(#{display}) {36}",
    "% git log -1 `git rev-list --all | xargs git grep '#{$1}' | tail -1 | ruby -e \"STDIN.each {|line| puts line[0..39] }\"` {36}",
    "$ (#{params})という文字列がはじめて出現した(バージョン|コミット)に一時的に戻す {36}",
    "% git checkout `git rev-list --all | xargs git grep '#{$1}' | tail -1 | ruby -e \"STDIN.each {|line| puts line[0..39] }\"` {36}",
    "$ (#{numbers})個前のバージョンに一時的に戻す {37}",
    "% git checkout HEAD~#{$1} {37}",
    "$ (#{numbers})日前の状態に一時的に戻す {37}",
    "% git checkout \"@{#{$1} days ago}\"  {37}",
    "$ (#{numbers})時間前の状態に一時的に戻す {37}",
    "% git checkout \"@{#{$1} hours ago}\"  {37}",
    "$ (#{numbers})分前の状態に一時的に戻す {37}",
    "% git checkout \"@{#{$1} mins ago}\"  {37}",
    "$ 「(#{params})」という文字列を含むファイルを捜す {38}",
    "% git grep '#{$1}' {38}",
    "$ 「(#{params})」という文字列を含むファイルを全履歴から捜す {38}",
    "% git rev-list --all | xargs git grep '#{$1}' {38}",
    "$ ブランチ名を(#{params})に変える {39}",
    "% git branch -m #{$1} {39}",
    "$ (1つ|ひとつ)前のコミットで(削除した|消した)(#{files})を(復元する|元に戻す) {43}",
    "% git checkout $(git rev-list -n 1 HEAD -- #{$2})^ -- #{$2} {43}",
    "$ 現在の状況を(#{display}) {44}",
    "% git status {44}",
    "$ 「(#{files})」というファイルを「(#{params})」という名前に(変更|移動|改名|リネーム)する {45}",
    "% git mv #{$1} #{$2} {45}",
    "$ ファイル「(#{files})」を(#{delete}) {46}",
    "% git rm #{$1} {46}",
    "$ 直前のコミットのコメントを修正する {49}",
    "% git commit --amend {49}",
    "$ (#{files})に(#{params})という名前が(出現した|書かれた)のはいつ？ {50}",
    "% git blame #{$1} | grep #{$2} {50}",
    "$ (#{params})という名前が(#{files})に(出現した|書かれた)のはいつ？ {50}",
    "% git blame #{$2} | grep #{$1} {50}",
    "$ これまで追加/削除された行数を表示する {51}",
    "% git log --numstat --pretty=\"%H\" | awk 'NF==3 {plus+=$1; minus+=$2} END {printf(\"+%d, -%d\\\\n\", plus, minus)}' {51}",
    "$ (#{files})に(#{params})という名前が(出現した|書かれた)のはいつ？ {53}",
    "% git blame #{$1} | grep #{$2} {53}",
    "$ ツリー状にログを表示する {54}",
    "% git log --graph --all --format=\"%x09%an%x09%h %d %s\" {54}",
    "$ 最初に「(#{params})」という文字列を含むコミットをした時から現在までに追加されたファイルはどれとどれ？ {55}",
    "% git log --oneline --date=iso-strict --format='%cd %s' | grep #{$1} | tail -1 | awk '{print $1}' | xargs githelp-changed {55}"
  ],
  "pages": [
    "このサイトについて",
    "やりたいことの例",
    "Git情報源",
    "意義",
    "関連文献",
    "gitコマンドに関する疑問",
    "Issues",
    "ブランチ",
    "gem版の使い方",
    "Glossary",
    "ファイルの編集回数のランキング",
    "Electron版GitHelp (2018版)",
    "レポジトリを確認する",
    "ファイルを大きい順に表示",
    "新しい順にファイルを表示",
    "古いファイルとの比較",
    "特定のファイルの履歴を消す",
    "最近の変更を知る",
    "ブランチのリストを更新日時順に表示する",
    "ファイルリスト",
    "Reset関連",
    "操作履歴",
    "branches",
    "タグ",
    "ブランチの表示",
    "アイデア",
    "Gitのマニュアルページ",
    "編集中のファイル",
    "レポジトリ",
    "コミットID",
    "コミット",
    "コミットをまとめる",
    "バージョン指定",
    "古いファイル表示",
    "最近編集したファイルのリストを表示する",
    "編集中のファイルをリストする",
    "文字列がはじめて出現したバージョンを捜す",
    "古いバージョンに一時的に戻す",
    "変数や単語が出現しているファイルを捜す",
    "ブランチ名",
    "ユーザ情報",
    "引数パラメタ",
    "リモートブランチを消す",
    "ファイル復元",
    "現在の状況",
    "ファイル名変更",
    "ファイル削除",
    "テンプレート",
    "一時的に仕事を退避",
    "コメント修正",
    "文字列の出現を調べる",
    "追加/削除された行数",
    "数字パラメタ",
    "文字列の出現判定",
    "ツリー状にログを表示する",
    "ファイル追加",
    "args",
    "増井俊之"
  ]
}
module.exports = data
