#!/usr/bin/env ruby
# -*- ruby -*-

require 'optparse'

$:.unshift "lib"
require 'helpline/helpline'
require 'helpline/update'
require 'helpline/generate'
require 'helpline/run'

# アップデート
#   % helpline -u
# データを指定してアップデート
#   % helpline -u HelpLine /Users/masui/ScrapboxData/masui-HelpLine.json
# テスト
#   % helpline -t args
#

helpline = HelpLine.new

options = ARGV.getopts('utds:','update','test','source:','debug')

#
# update
#
if options['u'] || options['update'] # ~/.helpline.json更新
  sources = (ARGV.length > 0 ? ARGV : ['HelpLine'])
  helpline.update sources
  exit
end

if options['t'] || options['test'] # テスト
  puts helpline.generate " #{ARGV.join(' ')} "
  exit
end

debug = options['d'] || options['debug']
query = " #{ARGV.join(' ').sub(/\[/,'').sub(/\]/,'')} "
helpline.run query, debug
