let suggests = [
   {content: 'https://Scrapbox.io/HelpLine/楽しくヘルプを書く', description: '楽しくヘルプを書く'},
   {content: 'https://Scrapbox.io/HelpLine/楽しくヘルプを書く', description: '楽しくヘルプを作成する'},
   {content: 'https://Scrapbox.io/HelpLine/楽しくヘルプを書く', description: 'ヘルプを楽しく書く'},
   {content: 'https://Scrapbox.io/HelpLine/楽しくヘルプを書く', description: 'ヘルプを楽しく作成する'},
   {content: 'http://0xcc.net/blog/archives/000043.html', description: '各種言語の配列操作ライブラリ'},
   {content: 'https://tenki.jp/forecast/3/17/4610/14204/3hours.html', description: '鎌倉の天気'},
   {content: 'https://tokyo-ame.jwa.or.jp/', description: '鎌倉の雨の様子を見る'},
   {content: 'https://scrapbox.io/SFCHelp/ラーメン', description: '湘南台のラーメン情報'},
   {content: 'https://www.k-cube.co.jp/wakaba/server/ascii_code.html', description: 'ASCIIコードを調べる'},
   {content: 'https://www.amazon.co.jp/gp/new-releases/books/2501045051/', description: 'Amazon新刊漫画ランキング'},
   {content: 'https://creepfablic.site/2019/10/13/bash-zsh/', description: 'zshの設定を調べる'},
   {content: 'https://www.server-memo.net/tips/crontab.html', description: 'crontabのフォーマット'},
   {content: '/Applications/EPKeygen.app', description: 'sshの秘密鍵id_rsaを暗号化してid_rsa.episopassを作る'},
   {content: '/Applications/EPKeygen.app', description: 'sshの秘密鍵を暗号化したid_rsa.episopassを復号してid_rsaを作る'},
   {content: 'https://www.kewpie.co.jp/recipes/', description: 'キューピーのおすすめレシピを見る'},
   {content: 'https://park.ajinomoto.co.jp/recipe/menu/weekly/', description: '味の素今週のレシピ'},
   {content: 'https://www.kikkoman.co.jp/homecook/index.html', description: 'キッコーマン 今日のレシピ'},
   {content: 'https://helpfeel.com/CrewGuide/', description: 'CrewのHelpfeelを見る'},
   {content: 'https://helpfeel.com/CrewGuide/', description: 'CrewのFAQを見る'},
   {content: 'https://help.ticket.st/', description: 'チケットストリートのHelpfeelを見る'},
   {content: 'https://help.ticket.st/', description: 'チケットストリートのFAQを見る'},
   {content: 'https://scrapbox.io/SFCHelp', description: 'SFCHelpのデータを編集する'},
   {content: 'https://helpfeel.com/pococha/', description: 'PocochaのHelpfeelを見る'},
   {content: 'https://helpfeel.com/pococha/', description: 'PocochaのFAQを見る'},
   {content: 'https://paypayfleamarket.yahoo.co.jp/help/', description: 'PayPayフリマのHelpfeelを見る'},
   {content: 'https://paypayfleamarket.yahoo.co.jp/help/', description: 'PayPayフリマのFAQを見る'},
   {content: 'http://gyatv.com/東京タワー', description: '東京タワーをスライドショーする'},
   {content: 'http://gyatv.com/東京タワー', description: '東京タワーのスクリーンセーバを#{display}'},
   {content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non orci accumsan, pulvinar risus sit amet, egestas felis. Praesent lobortis nulla nec fermentum tempus. Etiam tempus fermentum mattis. Curabitur scelerisque pharetra pulvinar. Duis maximus mattis fringilla. Suspendisse risus orci, convallis ac dui at, bibendum elementum massa. Donec ornare bibendum pharetra. Sed pretium placerat fringilla. Ut ac luctus felis. Pellentesque maximus dolor vitae velit convallis, sit amet hendrerit sapien feugiat.', description: 'Lorem Ipsumを表示'},
   {content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non orci accumsan, pulvinar risus sit amet, egestas felis. Praesent lobortis nulla nec fermentum tempus. Etiam tempus fermentum mattis. Curabitur scelerisque pharetra pulvinar. Duis maximus mattis fringilla. Suspendisse risus orci, convallis ac dui at, bibendum elementum massa. Donec ornare bibendum pharetra. Sed pretium placerat fringilla. Ut ac luctus felis. Pellentesque maximus dolor vitae velit convallis, sit amet hendrerit sapien feugiat.', description: 'Lipsum.comを表示'},
   {content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non orci accumsan, pulvinar risus sit amet, egestas felis. Praesent lobortis nulla nec fermentum tempus. Etiam tempus fermentum mattis. Curabitur scelerisque pharetra pulvinar. Duis maximus mattis fringilla. Suspendisse risus orci, convallis ac dui at, bibendum elementum massa. Donec ornare bibendum pharetra. Sed pretium placerat fringilla. Ut ac luctus felis. Pellentesque maximus dolor vitae velit convallis, sit amet hendrerit sapien feugiat.', description: 'Lorem ipsum dolor sit amet... を表示'},
   {content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non orci accumsan, pulvinar risus sit amet, egestas felis. Praesent lobortis nulla nec fermentum tempus. Etiam tempus fermentum mattis. Curabitur scelerisque pharetra pulvinar. Duis maximus mattis fringilla. Suspendisse risus orci, convallis ac dui at, bibendum elementum massa. Donec ornare bibendum pharetra. Sed pretium placerat fringilla. Ut ac luctus felis. Pellentesque maximus dolor vitae velit convallis, sit amet hendrerit sapien feugiat. | pbcopy', description: 'Lorem Ipsumをコピー'},
   {content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non orci accumsan, pulvinar risus sit amet, egestas felis. Praesent lobortis nulla nec fermentum tempus. Etiam tempus fermentum mattis. Curabitur scelerisque pharetra pulvinar. Duis maximus mattis fringilla. Suspendisse risus orci, convallis ac dui at, bibendum elementum massa. Donec ornare bibendum pharetra. Sed pretium placerat fringilla. Ut ac luctus felis. Pellentesque maximus dolor vitae velit convallis, sit amet hendrerit sapien feugiat. | pbcopy', description: 'Lipsum.comをコピー'},
   {content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non orci accumsan, pulvinar risus sit amet, egestas felis. Praesent lobortis nulla nec fermentum tempus. Etiam tempus fermentum mattis. Curabitur scelerisque pharetra pulvinar. Duis maximus mattis fringilla. Suspendisse risus orci, convallis ac dui at, bibendum elementum massa. Donec ornare bibendum pharetra. Sed pretium placerat fringilla. Ut ac luctus felis. Pellentesque maximus dolor vitae velit convallis, sit amet hendrerit sapien feugiat. | pbcopy', description: 'Lorem ipsum dolor sit amet... をコピー'},
   {content: 'http://bkclass.web.fc2.com/doc_vt100.html', description: 'VT100のエスケープシーケンス'},
   {content: 'http://dl.acm.org/', description: 'ACM Digital Libraryで論文検索'},
   {content: 'http://dl.acm.org/', description: '論文をACM Digital Libraryで検索'},
   {content: 'http://ci.nii.ac.jp/', description: 'CiNiiで論文検索'},
   {content: 'http://ci.nii.ac.jp/', description: '論文をCiNiiで検索'},
   {content: 'https://www.semanticscholar.org/', description: 'Semantic Scholarで論文検索'},
   {content: 'https://www.researchgate.net/', description: 'ResearchGateで論文検索'},
   {content: 'https://www.jstage.jst.go.jp/browse/-char/ja/', description: 'JStageで論文検索'},
   {content: 'http://0xcc.net/blog/archives/000137.html', description: '各種言語の文字列操作ライブラリ'},
   {content: 'https://scrapbox.io/forum-jp/', description: 'Scrapboxへのユーザからの要望を見る'},
   {content: 'https://scrapbox.io/forum-jp/', description: 'Scrapboxへのユーザからの要望を調べる'},
   {content: 'https://qiita.com/taka_hira/items/8a9181c0733de2c9f8ee', description: 'Kindleの書籍リストをCSVで取得する方法'},
   {content: 'https://Scrapbox.io/HelpLine/gron', description: 'JSONを展開してgrep可能にするgronというコマンド'},
   {content: 'https://tenki.jp/radar/3/17/', description: '神奈川県の天気/雨雲レーダー'},
   {content: 'https://tenki.jp/radar/3/17/', description: '神奈川県のtenki/雨雲レーダー'},
   {content: 'https://tenki.jp/radar/3/17/', description: '雨の状況を知る'},
   {content: 'https://tenki.jp/radar/3/17/', description: '雨雲の状況を知る'},
   {content: 'https://tenki.jp/radar/3/17/rainmesh.html', description: '神奈川県の天気/雨雲予報'},
   {content: 'https://tenki.jp/radar/3/17/rainmesh.html', description: '神奈川県のtenki/雨雲予報'},
   {content: 'https://www.youtube.com/watch?v=VzLIyf6n-rs', description: 'music: Night Streets （Chick Corea） Live under the sky'},
   {content: 'http://masui.org/03ed863e67f7d9ae31b67e8fe9d4be89.mp4', description: 'music: Invitation （小宅珠美）'},
   {content: 'https://youtube.com/watch?v=jt7nDVM_A54', description: 'music: Yesterdays （Dave Brubeck） Newport Jazz'},
   {content: 'http://youtube.com/watch?v=gcVMg2ynWYw', description: 'music: Inner Glimpse （McCoy Tyner）'},
   {content: 'http://masui.org.s3.amazonaws.com/7/9/79b9eca1089a04cf6eafe70686bed1b2.mp3', description: 'music: Tutu （Miles Davis）'},
   {content: 'https://www.internet-radio.com/stations/house/', description: 'music: ハウスを聞く'},
   {content: 'https://www.internet-radio.com/stations/house/', description: 'music: houseを聞く'},
   {content: 'https://youtube.com/watch?v=asA5mPZDCW8', description: 'music: Ai no corrida'},
   {content: 'https://youtube.com/watch?v=asA5mPZDCW8', description: 'music: 愛のコリーダ'},
   {content: 'https://www.youtube.com/watch?v=tPBDMihPRJA', description: 'music: Stomp （Brothers Johnson）'},
   {content: 'https://www.youtube.com/watch?v=sOnqjkJTMaA', description: 'music: Thriller （Michael Jackson）'},
   {content: 'https://www.youtube.com/watch?v=sOnqjkJTMaA', description: 'music:  スリラー （Michael Jackson）'},
   {content: 'https://www.youtube.com/watch?v=eHcIX54iLd0', description: 'music: Little Lou （Sonny Rollins Live Under The Sky 1981）'},
   {content: '13番の箱', description: 'パスポートの場所'},
   {content: '13番の箱', description: 'パスポートはどこ'},
   {content: '13番の箱', description: 'passportの場所'},
   {content: '13番の箱', description: 'passportはどこ'},
   {content: 'http://pitecan.com/p/Amazon_masui@pitecan.com.html', description: 'Amazonのパスワードを計算'},
   {content: 'http://pitecan.com/p/Amazon_masui@pitecan.com.html', description: 'Amazonのpasswordを計算'},
   {content: 'http://pitecan.com/p/Google_tmasui@gmail.com.html', description: 'Googleのパスワードを計算'},
   {content: 'http://pitecan.com/p/Google_tmasui@gmail.com.html', description: 'Googleのpasswordを計算'},
   {content: 'http://pitecan.com/p/GSuite_masui@pitecan.com.html', description: 'GSuiteのパスワードを計算'},
   {content: 'http://pitecan.com/p/GSuite_masui@pitecan.com.html', description: 'GSuiteのpasswordを計算'},
   {content: 'https://twitter.com/Che_SYoung', description: 'Twitter: 崔碩栄 サイケンエイ'},
   {content: 'https://twitter.com/Che_SYoung', description: 'Twitter: 崔碩栄 さいけんえい'},
   {content: 'https://twitter.com/Che_SYoung', description: 'Twitter: 崔碩栄 Sai Ken-ei'},
   {content: 'https://twitter.com/xcvbnm67890', description: 'Twitter: H.S. Kim'},
   {content: 'https://scrapbox.io/Serencast/Music', description: '手持ちの音楽リストを開く'},
   {content: 'https://scrapbox.io/Serencast/Music', description: '手持ちの音楽リストを見る'},
   {content: 'https://scrapbox.io/Serencast/Music', description: '手持ちのmusicリストを開く'},
   {content: 'https://scrapbox.io/Serencast/Music', description: '手持ちのmusicリストを見る'},
   {content: 'https://scrapbox.io/Serencast/Music', description: 'Serencastの音楽リストを開く'},
   {content: 'https://scrapbox.io/Serencast/Music', description: 'Serencastの音楽リストを見る'},
   {content: 'https://scrapbox.io/Serencast/Music', description: 'Serencastのmusicリストを開く'},
   {content: 'https://scrapbox.io/Serencast/Music', description: 'Serencastのmusicリストを見る'},
   {content: 'https://scrapbox.io/MasuiCast/Music', description: 'MasuiCastの音楽リストを開く'},
   {content: 'https://scrapbox.io/MasuiCast/Music', description: 'MasuiCastの音楽リストを見る'},
   {content: 'https://scrapbox.io/MasuiCast/Music', description: 'MasuiCastのmusicリストを開く'},
   {content: 'https://scrapbox.io/MasuiCast/Music', description: 'MasuiCastのmusicリストを見る'},
   {content: 'https://www.hulu.jp/watch/100009049', description: 'Anime: Just Because - 藤沢'},
   {content: 'chrome://extensions/', description: 'Chromeの拡張機能を開く'},
   {content: 'https://scrapbox.io/masui-bookmarks/', description: '増井のブックマーク集'},
   {content: 'https://scrapbox.io/masui-bookmarks/', description: '増井のbookmark集'},
   {content: 'https://Scrapbox.io/masui-helpline/三題噺ジェネレータ', description: 'Helpfeel記法から三題噺を生成する'},
   {content: 'https://Scrapbox.io/masui-helpline/RubyでHTTP', description: 'RubyでHTTP GETする'},
   {content: '26番の箱', description: '実印とか印鑑証明とかはどこ？'},
   {content: '367番のクリアフォルダ', description: '切手はどこ？'},
   {content: 'https://Scrapbox.io/masui-helpline/TODO', description: 'TODO: 確定申告'},
   {content: 'https://Scrapbox.io/toshiyukimasui/TODO', description: 'TODOを表示'},
   {content: '198319731', description: '情報処理学会会員番号'},
   {content: '37331701 | pbcopy ; open https://www.orix-carsharing.com/cev/default2.html', description: 'ORIXカーシェア car share'},
   {content: 'https://Scrapbox.io/masui-helpline/ScrapboxのCSS', description: 'Scrapboxのトップページのサイズバーとソート順を消す'},
   {content: 'https://qiita.com/taka_hira/items/8a9181c0733de2c9f8ee', description: 'Kindle本のリストを取得する'},
   {content: 'https://scrapbox.io/toshiyukimasui/%E5%90%84%E7%A8%AEID', description: '会員番号を調べる'},
   {content: 'https://scrapbox.io/toshiyukimasui/%E5%90%84%E7%A8%AEID', description: 'いろんなIDを調べる'},
   {content: 'https://scrapbox.io/masui-family/%E7%95%AA%E5%8F%B7%E6%95%B4%E7%90%86', description: '番号箱を検索する'},
   {content: 'https://scrapbox.io/masui-family/%E7%95%AA%E5%8F%B7%E6%95%B4%E7%90%86', description: '番号箱を捜す'},
   {content: 'https://scrapbox.io/masui-family/%E7%95%AA%E5%8F%B7%E6%95%B4%E7%90%86', description: '番号箱をさがす'},
   {content: 'https://scrapbox.io/masui-family/%E7%95%AA%E5%8F%B7%E6%95%B4%E7%90%86', description: 'クリアファイルを検索する'},
   {content: 'https://scrapbox.io/masui-family/%E7%95%AA%E5%8F%B7%E6%95%B4%E7%90%86', description: 'クリアファイルを捜す'},
   {content: 'https://scrapbox.io/masui-family/%E7%95%AA%E5%8F%B7%E6%95%B4%E7%90%86', description: 'クリアファイルをさがす'},
   {content: 'https://tabelog.com/kanagawa/A1404/A140404/14018222/', description: '辻堂の町中華「栄華」'},
   {content: 'https://tabelog.com/kanagawa/A1404/A140404/14018222/', description: '辻堂のレストラン「栄華」'},
   {content: 'https://www.alexa.com/siteinfo/scrapbox.io', description: 'AlexaでScrapboxのトラフィックを調べる'},
   {content: 'https://www.alexa.com/siteinfo/gyazo.com', description: 'AlexaでGyazoのトラフィックを調べる'},
   {content: 'https://scrapbox.io/masui-family/%E8%BE%BB%E5%A0%82%E3%81%AEHEMS', description: '辻堂のHEMSEchonet情報'},
   {content: '0466-53-9543', description: 'SSTのオリックスレンタカー'},
   {content: '0466-53-9543', description: 'SSTのORIXレンタカー'},
   {content: 'https://Scrapbox.io/masui/正規分布と冪分布', description: '書きかけブログ: 正規分布と冪分布'},
   {content: 'https://Scrapbox.io/masui/パソコンのセミコロンキーを改行キーにする', description: 'キーボードのセミコロンキーを改行キーにする'},
   {content: 'https://Scrapbox.io/masui/パソコンのセミコロンキーを改行キーにする', description: 'パソコンのセミコロンキーを改行キーにする'},
   {content: 'https://Scrapbox.io/masui/県名なぞなぞ', description: '県名なぞなぞ'},
   {content: 'https://Scrapbox.io/masui/発想法とScrapbox', description: 'ネタ ブレインストーミング ブレスト'},
   {content: 'https://Scrapbox.io/masui/2ホップリンクの考察', description: 'Scrapboxの2ホップリンクに関する考察'},
   {content: 'https://Scrapbox.io/masui/海外なぞなぞ', description: '海外なぞなぞ'},
   {content: 'https://Scrapbox.io/masui/文芸的プログラミング', description: '書きかけブログ: 文芸的プログラミング'},
   {content: 'https://Scrapbox.io/masui/自前のLinuxアプリにアイコンをつけてデスクトップから起動', description: '自前のLinuxアプリにアイコンをつけてデスクトップから起動'},
   {content: 'https://Scrapbox.io/masui/ChromeOSのバージョンを知る方法', description: 'ChromeOSのバージョンを知る'},
   {content: 'https://Scrapbox.io/masui/大物の評価', description: 'Richard Stallmanにウケなかった話'},
   {content: 'https://Scrapbox.io/masui/大物の評価', description: 'Donald Normanにウケなかった話'},
   {content: 'https://Scrapbox.io/masui/タージマハール症候群', description: 'タージマハール症候群'},
   {content: 'https://Scrapbox.io/masui/タージマハール症候群', description: 'ダメな経営者が無駄な社屋を作りがちな問題'},
   {content: 'https://Scrapbox.io/masui/FireTV StickでWebページにアクセスする', description: 'FireTV StickでWebページにアクセスする'},
   {content: 'https://Scrapbox.io/masui/EPSFを使って紙の上の正確な位置に図を描く', description: 'EPSFを使って紙の上の正確な位置に図を描く'},
   {content: 'https://Scrapbox.io/masui/ローカルにインストールしたgemを使う', description: 'Ruby: ローカルにインストールしたgemを使う'},
   {content: 'https://Scrapbox.io/toshiyukimasui/Rubyの日付フォーマット指定', description: 'Rubyの日付フォーマット指定'},
   {content: 'https://Scrapbox.io/toshiyukimasui/Rubyの呼び出し可能オブジェクトの比較', description: 'Rubyの呼び出し可能オブジェクトの比較'},
   {content: 'https://Scrapbox.io/toshiyukimasui/20191216105403', description: 'ブクマにHelpfeel記述を書く'},
   {content: 'https://Scrapbox.io/masuilab/omnibox', description: 'Chromeの検索テキストボックス = omnibox'},
   {content: 'https://Scrapbox.io/masuilab/omnibox', description: 'Chromeの検索テキストボックス = オムニボックス'},
   {content: 'https://Scrapbox.io/masuilab/omnibox', description: 'Chromeの検索枠 = omnibox'},
   {content: 'https://Scrapbox.io/masuilab/omnibox', description: 'Chromeの検索枠 = オムニボックス'},
   {content: 'https://Scrapbox.io/masuilab/omnibox', description: 'ChromeのURL表示テキストボックス = omnibox'},
   {content: 'https://Scrapbox.io/masuilab/omnibox', description: 'ChromeのURL表示テキストボックス = オムニボックス'},
   {content: 'https://Scrapbox.io/masuilab/omnibox', description: 'ChromeのURL表示枠 = omnibox'},
   {content: 'https://Scrapbox.io/masuilab/omnibox', description: 'ChromeのURL表示枠 = オムニボックス'},
   {content: 'https://Scrapbox.io/masuilab/関連学会リスト', description: 'USENIX'},
   {content: 'https://Scrapbox.io/masuilab/gron', description: 'JSONデータをgrepできるようにする'},
   {content: 'https://Scrapbox.io/masuilab/麺屋奨 TASUKU', description: '中央林間のつけ麺屋「TASUKU」'},
   {content: 'https://Scrapbox.io/masuilab/麺屋奨 TASUKU', description: '中央林間のラーメン「TASUKU」'},
   {content: 'https://Scrapbox.io/masui-bookmarks/UserCSS:レインボー記法 - suto3のネタ帳', description: 'Scrapbox: 行の色を虹色で表示する'},
   {content: 'https://Scrapbox.io/masui-bookmarks/UserCSS:レインボー記法 - suto3のネタ帳', description: 'Scrapbox: 行の色をレインボーカラーで表示する'},
   {content: 'https://Scrapbox.io/masui-bookmarks/お金ができる仕組み。銀行の詐欺システム(1/5) Money As Debt - YouTube', description: '銀行は詐欺'},
   {content: 'https://Scrapbox.io/masui-bookmarks/お金ができる仕組み。銀行の詐欺システム(1/5) Money As Debt - YouTube', description: '信用創造は詐欺'},
   {content: 'https://filler-color.akiroom.com/', description: '色つき矩形データのPNGを作成する'},
   {content: 'https://filler-color.akiroom.com/', description: '色つき矩形ファイルのPNGを作成する'},
   {content: 'https://filler-color.akiroom.com/', description: '色つき四角データのPNGを作成する'},
   {content: 'https://filler-color.akiroom.com/', description: '色つき四角ファイルのPNGを作成する'},
   {content: 'https://filler-color.akiroom.com/', description: '秋山氏作の矩形PNGファイル生成システム'},
   {content: 'https://filler-color.akiroom.com/', description: '秋山氏作の矩形PNGファイル作成システム'},
   {content: 'https://filler-color.akiroom.com/', description: '秋山氏作の四角PNGファイル生成システム'},
   {content: 'https://filler-color.akiroom.com/', description: '秋山氏作の四角PNGファイル作成システム'},
   {content: 'https://Scrapbox.io/masui-bookmarks/HTMLCanvasElement.toDataURL() - Web API | MDN', description: 'Canvasデータを画像のData URIにする'},
   {content: 'https://Scrapbox.io/masui-bookmarks/HTMLCanvasElement.toDataURL() - Web API | MDN', description: 'Canvasデータを画像ファイルにする'},
   {content: 'https://Scrapbox.io/masui-bookmarks/HTMLCanvasElement.toDataURL() - Web API | MDN', description: 'Canvasデータを画像のData URIに変換する'},
   {content: 'https://Scrapbox.io/masui-bookmarks/HTMLCanvasElement.toDataURL() - Web API | MDN', description: 'Canvasデータを画像ファイルに変換する'},
   {content: 'https://Scrapbox.io/masui-bookmarks/ネタ', description: '各種ネタ情報'},
   {content: 'https://Scrapbox.io/masui-bookmarks/Scrapboxに埋め込めるドローイングアプリ: Kakeruの話 - イワモト=カイドウ', description: '岩本海堂氏のお絵描きプログラム「Kakeru」 Scrapbox'},
   {content: 'https://Scrapbox.io/masui-bookmarks/明治大学中村氏のプログラミング演習', description: '明治大学中村氏のプログラミング演習'},
   {content: 'https://Scrapbox.io/masui-bookmarks/やしの実通信 by Dr Rieko Hayakawa', description: 'やしの実通信 太平洋方面ニュース'},
   {content: 'https://Scrapbox.io/masui-bookmarks/華麗なる一族 みんなのクレジット - Life=Risk', description: '河口洋一郎や千住博とトラブルになっている銀座の白石ギャラリー「ホワイトストーン」'},
   {content: 'https://Scrapbox.io/masui-bookmarks/Proxy - JavaScript | MDN', description: 'JavaScript: Rubyのmethod_missingみたいなことをする'},
   {content: 'https://Scrapbox.io/masui-bookmarks/audio - Disable beep/chime in Secure Shell in Chrome OS - Unix & Linux Stack Exchange', description: 'Chromebook: ターミナルのベル音を消す'},
   {content: 'https://Scrapbox.io/masui-bookmarks/コードブロックのjsを実行するUserScript - 🍊miyamonz🍊', description: 'Scrapbox: 別ページに飛ばずにコードブロックのJavaScriptを実行する'},
   {content: 'https://Scrapbox.io/masui-bookmarks/異世界ものマンガを25作品ほどまとめて紹介します - 頭の上にミカンをのせる', description: '異世界モノマンガ'},
   {content: 'https://Scrapbox.io/masui-bookmarks/「生ビールがあるのになんで瓶ビールってあるんだろう」→この漫画を読むと瓶ビールが飲みたくなる！ | いいね！ニュース', description: '生ビールと瓶ビール'},
   {content: 'https://Scrapbox.io/masui-bookmarks/「生ビールがあるのになんで瓶ビールってあるんだろう」→この漫画を読むと瓶ビールが飲みたくなる！ | いいね！ニュース', description: '生ビールとビンビール'},
   {content: 'https://Scrapbox.io/masui-bookmarks/中村匡氏講義資料', description: '中村匡氏の講義リンク集'},
   {content: 'https://Scrapbox.io/masui-bookmarks/中村匡氏講義資料', description: '中村匡氏のサイエンスリンク集'},
   {content: 'https://Scrapbox.io/masui-bookmarks/中村匡氏講義資料', description: '中村匡氏の講義関連URLまとめ'},
   {content: 'https://Scrapbox.io/masui-family/青田風', description: '青田風'},
   {content: 'https://Scrapbox.io/masui-family/青田風', description: 'aotakaze'},
]
